# Generated by Django 4.2.11 on 2026-02-20 17:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Generated or user-provided title", max_length=300
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "topic_input",
                    models.CharField(
                        help_text="Original user topic/keyword input", max_length=500
                    ),
                ),
                (
                    "raw_prompt",
                    models.TextField(
                        help_text="Full prompt sent to AI (includes persona injection)"
                    ),
                ),
                (
                    "generated_content",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated blog post in Markdown format",
                    ),
                ),
                (
                    "content_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed structure: headings, word_count, reading_time",
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of source objects with url, title, domain, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.IntegerField(
                        default=0, help_text="Derived: likes - dislikes"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible storage for generation metadata",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=300)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("dislikes_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                (
                    "engagement_rate",
                    models.FloatField(
                        default=0.0, help_text="(likes + shares) / views"
                    ),
                ),
                (
                    "scroll_depth_avg",
                    models.FloatField(help_text="Avg scroll percentage", null=True),
                ),
                ("read_completion_rate", models.FloatField(null=True)),
                ("seo_score", models.IntegerField(null=True)),
                ("ranking_position", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Metric",
                "verbose_name_plural": "Post Metrics",
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "persona_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Writer"),
                            ("narrative", "Storyteller"),
                            ("analyst", "Industry Analyst"),
                            ("educator", "Educator"),
                            ("creative", "Creative Writer"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="Base system prompt for this persona"),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="User-facing description", max_length=300
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, help_text="Creativity: 0.0-1.0"),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=4000, help_text="Max output tokens"),
                ),
                ("top_p", models.FloatField(default=0.9, help_text="Nucleus sampling")),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="blog_person_slug_f43b91_idx"),
                    models.Index(
                        fields=["is_active"], name="blog_person_is_acti_d3bb4e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="UUID from client localStorage",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                    ),
                ),
                (
                    "action_value",
                    models.IntegerField(default=1, help_text="Weight of this action"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="User agent, referrer, etc."
                    ),
                ),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="persona",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to="blog.persona",
            ),
        ),
        migrations.CreateModel(
            name="SourceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.CharField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI-assigned relevance (0.0-1.0)",
                        null=True,
                    ),
                ),
                ("usage_count", models.IntegerField(default=1)),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_references",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="blog_source_domain_cd24bf_idx"
                    ),
                    models.Index(
                        fields=["blog_post", "relevance_score"],
                        name="blog_source_blog_po_8efaf5_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcereference",
            constraint=models.UniqueConstraint(
                fields=("blog_post", "url"),
                name="unique_source_per_post",
                violation_error_message="This source is already added to this post.",
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["blog_post", "action"], name="blog_engage_blog_po_0dcc21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["session_id"], name="blog_engage_session_a05c0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["created_at"], name="blog_engage_created_8ca555_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagement",
            constraint=models.UniqueConstraint(
                fields=("blog_post", "session_id", "action"),
                name="unique_engagement_per_session",
                violation_error_message="You have already performed this action.",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="blog_blogpo_slug_361555_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["status"], name="blog_blogpo_status_9c1956_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["-created_at"], name="blog_blogpo_created_2e77d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["sentiment_score"], name="blog_blogpo_sentime_f2d692_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["persona", "status"], name="blog_blogpo_persona_2d3ec1_idx"
            ),
        ),
    ]
