# Generated by Django 4.2.11 on 2026-02-20 20:18

from django.db import migrations, models
import django.db.models.deletion


def dedupe_engagement_rows(apps, schema_editor):
    Engagement = apps.get_model('blog', 'Engagement')
    seen = set()
    for row in Engagement.objects.order_by('blog_post_id', 'session_id', '-created_at', '-id'):
        key = (row.blog_post_id, row.session_id)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=500)),
                ('persona_slug', models.SlugField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('speed', models.CharField(default='fast', max_length=10)),
                ('additional_context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='engagement',
            name='unique_engagement_per_session',
        ),
        migrations.RunPython(dedupe_engagement_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('blog_post', 'session_id'), name='unique_engagement_per_session', violation_error_message='Session engagement already exists for this post.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='blog.blogpost'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['status', '-created_at'], name='blog_genera_status_74bf37_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['persona_slug'], name='blog_genera_persona_2ca0dd_idx'),
        ),
    ]
